---
- name: "Get Newest Terraform Version"
  uri:
    url: https://api.github.com/repos/hashicorp/terraform/releases/latest
    body_format: json
  register: terra
  tags: terraform

- name: "Terraform Version"
  debug:
    msg: "{{ terra.json.tag_name | replace ('v', '') }}"
  tags: terraform

- name: "Set Terraform Version"
  set_fact:
    terraver: "{{ terra.json.tag_name | replace ('v', '') }}"
  tags: terraform

- name: "Download Terraform amd64"
  get_url:
    url: "https://releases.hashicorp.com/terraform/{{ terraver }}/terraform_{{ terraver }}_linux_amd64.zip"
    dest: /tmp/terraform-{{ terraver }}.zip
    mode: 0777
  tags: terraform

- name: "Install Terraform"
  unarchive:
    src: /tmp/terraform-{{ terraver }}.zip
    dest: /usr/bin/
    mode: +x
    remote_src: true
  become: true
  tags: terraform
